const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#3B5BDB",
    background: "#F8F9FA",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#3B5BDB",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#3B5BDB",
    muted: "#F1F3F5",
    mutedForeground: "#868E96",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#FA5252",
    destructiveForeground: "#FFFFFF",
    border: "#E9ECEF",
    input: "#E9ECEF",
    success: "#40C057",
    successForeground: "#FFFFFF",
    warning: "#FAB005",
    warningForeground: "#FFFFFF",
  },
  dark: {
    text: "#F1F3F5",
    tint: "#4C6EF5",
    background: "#0F1117",
    foreground: "#F1F3F5",
    card: "#1A1B2E",
    cardForeground: "#F1F3F5",
    primary: "#4C6EF5",
    primaryForeground: "#FFFFFF",
    secondary: "#1C2A4A",
    secondaryForeground: "#74C0FC",
    muted: "#1E2230",
    mutedForeground: "#ADB5BD",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#FF6B6B",
    destructiveForeground: "#FFFFFF",
    border: "#2C2E45",
    input: "#2C2E45",
    success: "#51CF66",
    successForeground: "#FFFFFF",
    warning: "#FFD43B",
    warningForeground: "#1A1A2E",
  },
  radius: 12,
};

export default colors;
